---
- name: Install Docker
  yum:
    name: docker
    state: present

- name: Start Docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Add ec2-user to docker group
  user:
    name: ec2-user
    groups: docker
    append: yes

- name: Install Git
  yum:
    name: git
    state: present

- name: Install Docker Compose
  shell: |
    curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose
  args:
    creates: /usr/local/bin/docker-compose

- name: Clone Repository
  git:
    repo: "{{ repo_url }}"
    dest: "{{ app_dir }}"
    force: yes

- name: Deploy App
  shell: |
    cd {{ app_dir }}
    docker compose up -d --build
  notify: Check containers
