---
- name: Install required packages
  yum:
    name:
      - docker
      - git
      - nginx
      - python3-pip
    state: present

- name: Start Docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Add ec2-user to docker group
  user:
    name: ec2-user
    groups: docker
    append: yes

- name: Install Docker Compose Plugin
  shell: |
    mkdir -p /usr/local/lib/docker/cli-plugins
    curl -SL "https://github.com/docker/compose/releases/download/v2.24.0/docker-compose-linux-x86_64" -o /usr/local/lib/docker/cli-plugins/docker-compose
    chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
    ln -sf /usr/local/lib/docker/cli-plugins/docker-compose /usr/bin/docker-compose

- name: Remove old directory
  file:
    path: "{{ app_dir }}"
    state: absent

- name: Clone Repository
  git:
    repo: "{{ repo_url }}"
    dest: "{{ app_dir }}"
    force: yes

- name: Set permissions
  file:
    path: "{{ app_dir }}"
    owner: ec2-user
    group: ec2-user
    recurse: yes

- name: Deploy App
  shell: |
    cd {{ app_dir }}
    docker compose up -d --build
  become_user: ec2-user
  environment:
    HOME: /home/ec2-user

- name: Copy ShopEasy frontend to Nginx
  copy:
    src: "{{ app_dir }}/frontend/index.html"
    dest: /usr/share/nginx/html/index.html
    remote_src: yes

- name: Start Nginx
  service:
    name: nginx
    state: restarted
    enabled: yes
